# server config
server:
  port: 8001

# oracle driver config
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@oracle.team-greedy.com:1521:xe
    username: C##JAEGOJAEGO
    password: JAEGOJAEGO
    hikari:
      auto-commit: false

# jpa config
# ddl-auto: validate 혹은 ddl-auto: none만 사용하세요, create, crate-drop, update, drop 사용 시 엔티티와 매핑된 모든 테이블 삭제됨(절대 사용하지 마세요)
  jpa:
    generate-ddl: false
    show-sql: true
    database: oracle
    properties:
      hibernate:
        '[format_sql]': true
    hibernate:
      ddl-auto: none

  #Live Reload 기능 활성화
  devtools:
    livereload:
      enabled: true

  web:
    resources:
      static-locations: file:src/main/resources/static/

  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/